name: OpenRouter Issue Triage
description: "Automatically triage GitHub issues using OpenRouter"

on:
  issues:
    types: [opened]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OpenRouter Issue Triage
        uses: ./.github/actions/claude-issue-triage-action
        with:
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
          model_name: 'google/gemini-flash-1.5'
          github_token: ${{ secrets.GITHUB_TOKEN }}
