name: OpenRouter General Task

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  llm_task_job: # Renamed job for consistency
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@llm')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@llm')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@llm')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@llm') || contains(github.event.issue.title, '@llm')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run LLM Task
        id: llm_task
        uses: ./.github/actions/openrouter-llm-action
        with:
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
          model_name: 'google/gemini-flash-1.5'
          prompt: |
            Summarize the following GitHub event content. If it's an issue or PR comment, focus on the comment's main points. If it's an issue or PR body, summarize the description.
            Event Name: ${{ github.event_name }}
            Content:
            ${{ github.event.comment.body || github.event.issue.body || github.event.pull_request.body || github.event.review.body }}

            Provide a concise summary:
          github_token: ${{ secrets.GITHUB_TOKEN }} # The OpenRouter action might need this if the prompt instructs it to interact with GitHub
